edc_export/urls.py
from django.urls.conf import re_path, path

from .admin_site import edc_export_admin
from .views import HomeView, ExportModelsView, ExportSelectedModelsView

app_name = "edc_export"

urlpatterns = [
    path("admin/", edc_export_admin.urls),
    path(
        "selected_models/",
        ExportSelectedModelsView.as_view(),
        name="export_selected_models_url",
    ),
    re_path(
        "models/(?P<action>cancel|confirm)/",
        ExportModelsView.as_view(),
        name="export_models_url",
    ),
    re_path("models/", ExportModelsView.as_view(), name="export_models_url"),
    path("", HomeView.as_view(), name="home_url"),
]

edc_export/models/data_request.py
from django.apps import apps as django_apps
from django.db import models
from edc_model.models import BaseUuidModel, HistoricalRecords

from ..choices import EXPORT_FORMATS
from ..constants import CSV
from ..model_options import ModelOptions


class DataRequest(BaseUuidModel):

    name = models.CharField(max_length=25)

    description = models.TextField(null=True)

    decrypt = models.BooleanField(default=False)

    export_format = models.CharField(max_length=25, choices=EXPORT_FORMATS, default=CSV)

    models = models.TextField(
        help_text='List one table per line, no commas. Use "label lower" format.'
    )

    history = HistoricalRecords()

    def __str__(self):
        return self.name

    @property
    def models_as_list(self):
        """Returns `models` as a list of ModelOptions instances.

        Validates each item to be a model name.
        """
        models_as_list = self.models.split("\n")
        models_as_list = [x.strip() for x in models_as_list if x.strip()]
        for model in models_as_list:
            django_apps.get_model(model)
        return [ModelOptions(x) for x in models_as_list]

    class Meta:
        ordering = ("name",)

edc_export/models/data_request_history.py
from django.db import models
from django.db.models.deletion import PROTECT
from edc_model.models import BaseUuidModel
from edc_utils import get_utcnow

from .data_request import DataRequest


class DataRequestHistory(BaseUuidModel):

    data_request = models.ForeignKey(DataRequest, on_delete=PROTECT)

    archive_filename = models.CharField(max_length=200, null=True)

    emailed_to = models.EmailField(null=True)

    emailed_datetime = models.DateTimeField(null=True)

    summary = models.TextField(null=True)

    exported_datetime = models.DateTimeField(default=get_utcnow)

    class Meta:
        ordering = ("-exported_datetime",)
        verbose_name = "Data Request History"
        verbose_name_plural = "Data Request History"

edc_export/models/export_receipt.py
from django.db import models
from edc_model.models import BaseUuidModel, HistoricalRecords


class ExportReceiptManager(models.Manager):
    def get_by_natural_key(self, export_uuid):
        return self.get(export_uuid=export_uuid)


class ExportReceipt(BaseUuidModel):

    export_uuid = models.UUIDField(
        editable=False, help_text="system field for export tracking."
    )

    model = models.CharField(max_length=64)

    tx_pk = models.CharField(max_length=36)

    timestamp = models.CharField(max_length=50, null=True)

    received_datetime = models.DateTimeField(null=True, help_text="date ACK received")

    objects = ExportReceiptManager()

    history = HistoricalRecords()

    def __str__(self):
        return f"{self.model_name}.{self.export_uuid}"

    def natural_key(self):
        return (self.export_uuid,)

    class Meta:
        ordering = ("-timestamp",)

edc_export/models/file_history.py
from uuid import uuid4

from django.db import models
from django.utils import timezone
from edc_model.models import BaseUuidModel, HistoricalRecords


class FileHistoryManager(models.Manager):
    def get_by_natural_key(self, history_uuid):
        return self.get(history_uuid=history_uuid)


class FileHistory(BaseUuidModel):

    history_uuid = models.UUIDField(
        editable=False,
        default=uuid4,
        unique=True,
        help_text="system field for export tracking.",
    )

    model = models.CharField(max_length=50)

    export_uuid_list = models.TextField(
        null=True, help_text="list of export_uuid's of model app_label.model_name"
    )

    pk_list = models.TextField(
        null=True, help_text="list of pk's of model app_label.model_name"
    )

    exit_message = models.CharField(
        max_length=250, help_text="exit message from the export_transactions command"
    )

    exit_status = models.IntegerField(
        null=True, help_text="0=success, 1=failed from the export_transactions command"
    )

    filename = models.CharField(max_length=250, help_text="original filename on export")

    file_contents = models.TextField(
        null=True, help_text="save contents of file as a list of rows"
    )

    exported = models.BooleanField(default=False, help_text="exported to a file")

    exported_datetime = models.DateTimeField(null=True)

    notification_plan_name = models.CharField(max_length=50, null=True)

    sent = models.BooleanField(default=False, help_text="export file sent to recipient")

    sent_datetime = models.DateTimeField(null=True)

    received = models.BooleanField(
        default=False, help_text="have received an ACK from the recipient"
    )

    received_datetime = models.DateTimeField(null=True)

    closed = models.BooleanField(default=False, help_text="exported, sent, received")

    closed_datetime = models.DateTimeField(null=True)

    objects = FileHistoryManager()

    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        if self.sent and self.received and self.exported and not self.closed:
            self.closed = True
            self.closed_datetime = timezone.now()
        super().save(*args, **kwargs)

    def natural_key(self):
        return (self.history_uuid,)

    class Meta:
        ordering = ("-sent_datetime",)

edc_export/models/import_export.py
from django.db import models


class ExportData(models.Model):
    """Dummy model for permissions"""

    class Meta:
        permissions = [("show_export_admin_action", "Show export action")]


class ImportData(models.Model):
    """Dummy model for permissions"""

    class Meta:
        permissions = [("show_import_admin_action", "Show import action")]

edc_export/models/plan.py
from django.apps import apps as django_apps
from django.db import models
from edc_model.models import BaseUuidModel, HistoricalRecords

MODEL_TYPES = (
    ("consent", "Consent"),
    ("crf", "CRF"),
    ("locator", "Locator"),
    ("plain", "Plain"),
)


class PlanManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class Plan(BaseUuidModel):

    name = models.CharField(max_length=25, unique=True)

    model = models.CharField(max_length=50)

    field_names = models.TextField(max_length=500, blank=True, null=True)

    header_labels = models.TextField(max_length=500, blank=True, null=True)

    lookups = models.TextField(max_length=500, blank=True, null=True)

    model_type = models.CharField(max_length=25, choices=MODEL_TYPES, default="plain")

    excluded_field_names = models.TextField(max_length=500, blank=True, null=True)

    header = models.BooleanField(verbose_name="Include header", default=True)

    encrypt = models.BooleanField(verbose_name="Mask encrypted values", default=True)

    objects = PlanManager()

    history = HistoricalRecords()

    def __str__(self):
        return f"{self.name} {self.model}"

    def save(self, *args, **kwargs):
        model_cls = django_apps.get_model(self.model)
        if not self.field_names:
            self.field_names = [f.name for f in model_cls._meta.get_fields()]
            self.field_names = ",".join(self.field_names)
        if not self.header_labels:
            self.header_labels = [f.name for f in model_cls._meta.get_fields()]
            self.header_labels = ",".join(self.header_labels)
        super().save(*args, **kwargs)

    def natural_key(self):
        return (self.name,)

edc_export/forms/data_request_form.py
from django import forms
from django.apps import apps as django_apps
from edc_form_validators import FormValidator, FormValidatorMixin

from ..models import DataRequest


class DataRequestFormValidator(FormValidator):

    pass


class DataRequestForm(FormValidatorMixin, forms.ModelForm):

    form_validator_cls = DataRequestFormValidator

    def clean(self):
        cleaned_data = super().clean()
        if self.cleaned_data.get("requested"):
            requested = self.cleaned_data.get("requested").split("\n")
            requested = [x.strip() for x in requested if x.strip()]
            for model in requested:
                try:
                    django_apps.get_model(model)
                except (LookupError, ValueError):
                    raise forms.ValidationError(f"Invalid model. Got '{model}'")
        return cleaned_data

    class Meta:
        model = DataRequest
        fields = "__all__"

edc_export/views/export_models_view.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar import NavbarViewMixin

from ..exportables import Exportables


class ExportModelsView(EdcViewMixin, NavbarViewMixin, TemplateView):

    template_name = f"edc_export/bootstrap{settings.EDC_BOOTSTRAP}/export_models.html"
    navbar_name = "edc_export"
    navbar_selected_item = "export"

    def get_context_data(self, **kwargs):
        if self.kwargs.get("action") == "cancel":
            try:
                self.request.session.pop("selected_models")
            except KeyError:
                pass
            else:
                messages.info(self.request, "Nothing has been exported.")
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username=self.request.user)
        context.update(exportables=Exportables(request=self.request, user=user))
        return context

edc_export/views/export_selected_models_view.py
from datetime import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.utils.safestring import mark_safe
from django.views.generic.base import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin

from ..archive_exporter import ArchiveExporter, ArchiveExporterNothingExported
from ..archive_exporter import ArchiveExporterEmailError
from ..exportables import Exportables
from ..files_emailer import FilesEmailerError
from ..model_options import ModelOptions
from ..models import DataRequest, DataRequestHistory


class NothingToExport(Exception):
    pass


class ExportModelsViewError(Exception):
    pass


class ExportSelectedModelsView(EdcViewMixin, TemplateView):

    post_action_url = "edc_export:export_models_url"
    template_name = f"edc_export/bootstrap{settings.EDC_BOOTSTRAP}/export_models.html"

    def __init__(self, *args, **kwargs):
        self._selected_models_from_post = None
        self._selected_models_from_session = None
        self._selected_models = None
        self._user = None
        super().__init__(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.session.get("selected_models"):
            context.update(
                selected_models=[
                    ModelOptions(**dct)
                    for dct in self.request.session["selected_models"]
                ]
            )
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.email:
            user_url = reverse("admin:auth_user_change", args=(request.user.id,))
            messages.error(
                request,
                mark_safe(
                    "Your account does not include an email address. "
                    f'Please update your <a href="{user_url}">user account</a> '
                    "and try again."
                ),
            )
        else:
            try:
                self.export_models(request=request, email_to_user=True)
            except NothingToExport:
                selected_models = self.get_selected_models_from_post()
                if selected_models:
                    self.request.session["selected_models"] = selected_models
                else:
                    messages.warning(
                        request,
                        "Nothing to do. Select one or more models and try again.",
                    )
            except FilesEmailerError as e:
                messages.error(
                    request, f"Failed to send the data you requested. Got '{e}'"
                )
        url = reverse(self.post_action_url, kwargs=self.kwargs)
        return HttpResponseRedirect(url)

    def check_export_permissions(self, selected_models):
        return selected_models

    def export_models(self, request=None, email_to_user=None):
        selected_models = self.check_export_permissions(
            self.get_selected_models_from_session()
        )
        selected_models = [x.label_lower for x in selected_models]
        email_to_user = False if settings.DEBUG else email_to_user
        archive = True if settings.DEBUG else False
        try:
            exporter = ArchiveExporter(
                models=selected_models,
                add_columns_for=["subject_visit_id", "requisition_id"],
                user=self.user,
                request=request,
                email_to_user=email_to_user,
                archive=archive,
            )
        except (ArchiveExporterEmailError, ConnectionRefusedError) as e:
            messages.error(self.request, f"Failed to send files by email. Got '{e}'")
        except ArchiveExporterNothingExported:
            messages.info(self.request, "Nothing to export.")
        else:

            if email_to_user:
                msg = (
                    f"Your data request has been sent to {self.user.email}. "
                    "Please check your email."
                )
            elif archive:
                msg = (
                    f"Your data request has been saved to {exporter.archive_filename}. "
                )

            messages.success(request, msg)
            summary = [str(x) for x in exporter.exported]
            summary.sort()
            data_request = DataRequest.objects.create(
                name=f'Data request {datetime.now().strftime("%Y%m%d%H%M")}',
                models="\n".join(selected_models),
                user_created=self.user.username,
            )
            DataRequestHistory.objects.create(
                data_request=data_request,
                exported_datetime=exporter.exported_datetime,
                summary="\n".join(summary),
                user_created=self.user.username,
                user_modified=self.user.username,
                archive_filename=exporter.archive_filename,
                emailed_to=exporter.emailed_to,
                emailed_datetime=exporter.emailed_datetime,
            )

    @property
    def allowed_selected_models(self):
        """Returns a list of selected models as ModelOptions.
        """
        if self._selected_models:
            selected_models = self.get_selected_models_from_session()
            self._selected_models = self.check_export_permissions(selected_models)
        return self._selected_models or []

    def get_selected_models_from_post(self):
        """Returns a list of selected models from the POST
        as ModelOptions.
        """
        exportables = Exportables(request=self.request, user=self.user)
        selected_models = []
        for exportable in exportables:
            # pdb.set_trace()
            selected_models.extend(
                self.request.POST.getlist(f"chk_{exportable}_models") or []
            )
            selected_models.extend(
                self.request.POST.getlist(f"chk_{exportable}_historicals") or []
            )
            selected_models.extend(
                self.request.POST.getlist(f"chk_{exportable}_lists") or []
            )
            selected_models.extend(
                self.request.POST.getlist(f"chk_{exportable}_inlines") or []
            )
        return [ModelOptions(model=m).__dict__ for m in selected_models if m]

    def get_selected_models_from_session(self):
        """Returns a list of selected models from the session object
        as ModelOptions.
        """
        try:
            selected_models = self.request.session.pop("selected_models")
        except KeyError:
            raise NothingToExport("KeyError")
        else:
            if not selected_models:
                raise NothingToExport("Nothing to export")
        return [ModelOptions(**dct) for dct in selected_models]

    @property
    def user(self):
        """Returns an instance of the User model.
        """
        if not self._user:
            self._user = User.objects.get(username=self.request.user)
        return self._user

edc_export/views/home_view.py
from django.conf import settings
from django.views.generic import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar import NavbarViewMixin


class HomeView(EdcViewMixin, NavbarViewMixin, TemplateView):

    template_name = f"edc_export/bootstrap{settings.EDC_BOOTSTRAP}/home.html"
    navbar_name = "edc_export"
    navbar_selected_item = "export"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

edc_export/templates/edc_export/bootstrap3/export_models.html
{% extends edc_base_template %}
{% load static %}

{% block extra-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'edc_export/edc.css' %}"> 
{% endblock extra-css %}

{% block scripts %}
{{ block.super }}
    <script type="text/javascript" charset="utf8" src="{% static 'edc_export/edc.js' %}"></script>
{% endblock scripts %}


{% block main %}

{% if not perms.edc_dashboard.view_export_dashboard %}
	<div class="row">
	<div class="col-sm-12">
	<p class="text-center">You do not have sufficient permissions to view.</p>
	</div>
	</div>

{% else %}

{% if request.session.selected_models %}

	<div class="row">
	<div class="col-sm-12">
	<div id="work-in-progress"></div>
	<form method="post" action="{% url 'edc_export:export_selected_models_url' %}">
		<div class="form-group">

	 		<div class="panel panel-warning">
	 		<div class="panel-heading clearfix">
	 			<i class="fas fa-file-export fa-fw fa-lg"></i> 
	 		</div>
	 		</div>
	 		
			<div class="col-sm-3"></div>
			<div class="col-sm-6">
		 		<div class="panel">
		 		<div class="panel-body">
					<p class="text-center">
						Data from the models listed below are ready to send to you at<BR><B>{{ user.email }}</B>.
					<BR><BR>
					<a id="btn-cancel" role="button" href="{% url 'edc_export:export_models_url' action='cancel' %}" class="btn btn-default btn-sm"> Cancel </a>
					<button id="btn-confirm" class="btn btn-primary btn-sm" onclick="confirm();submit();return true;"> Confirm </button>
					{% if request.session.selected_models|length > 10 %}
						<BR><BR><small>Note: Since you have selected more than 10 models, your data will be sent over multiple emails each with no more than 10 attachments.</small>
					{% endif %}
					</p>
					{% csrf_token %}
		 		</div>
		 		</div>
	 		</div>
	 		<div class="col-sm-3"></div>
		</div>
	</form>
	</div>
	</div>

	<div class="row">
 	<div class="table-responsive">
	<table class="table table-condensed">
		<th>#</th>
		<th>Model</th>
		<th>Table</th>
		<th>App</th>
		{% for model in request.session.selected_models %}
			<tr>
				<td>{{ forloop.counter }}</td>
				<td>{{ model.verbose_name|title }}</td>
				<td>{{ model.db_table }}</td>
				<td>{{ model.app_name|title }}</td>
			</tr>
		{% endfor %}
	</table>
	</div>
	</div>
	</div>

{% else %}

	{% if exportables %}
		<div class="row">
		<div class="col-sm-12">

		<form id="frm_exportables" name="frm_exportables" method="post" action="{% url 'edc_export:export_selected_models_url' %}">
		<div class="form-group">
	 	
	 		<div class="panel panel-warning">
	 		<div class="panel-heading clearfix">
		        <a id="home_list_group_home" href="{% url 'edc_export:home_url' %}" class="btn btn-primary"><i class="fas fa-reply fa-fw" aria-hidden="true"></i></a>
	 			<button type="submit" class="btn btn-primary btn-sm pull-right">Export Selected</button>
	 		</div>
	 		</div>

		<div class="table-responsive">

		{% csrf_token %}

		{% for exportable in exportables.values %}

			<input type="hidden" name="app_config_name" value="{{ exportable.name }}" form="frm_exportables">

	 		<div class="panel panel-default">
	 		<div class="panel-heading clearfix"><b>{{ exportable.verbose_name }}</b>&nbsp;<small>({{ exportable.name }})</small>
	 		</div>
			<div class="panel-body">
				<div class="form-group">		

			<table class="table table-hover table-condensed">
			{% for label, models in exportable.items %}
				{% if models %}
					<tr><td colspan=4 class="text"><b>{{ label|title }}</b></td></tr>
					{% if models|length > 1 %}
						<tr>
							<td>
								<input id="select_all_{{ exportable.name }}_{{ label }}"
									type="checkbox" title="select all"
									onchange="selectAll('{{exportable.name}}','{{ label }}');" />&nbsp;
							</td>
							<td class="text text-muted text-uppercase small text-left" onclick="toggle('select_all_{{ exportable.name }}_{{ label }}');selectAll('{{exportable.name}}','{{ label }}');">select all</td>
							<td colspan=2 onclick="toggle('select_all_{{ exportable.name }}_{{ label }}');selectAll('{{exportable.name}}','{{ label }}');"></td>
						 </tr>
					{% endif %}
					{% for model in models %}
						<tr>
							<td>
								<input id="chk_{{ exportable.name }}_{{ label }}_{{ forloop.counter }}"
									name="chk_{{ exportable.name }}_{{ label }}"
									type="checkbox" value="{{ model.label_lower }}"
									form="frm_exportables"/>
							</td>
							<td onclick="toggle('chk_{{ exportable.name }}_{{ label }}_{{ forloop.counter }}');" class="text text-left align-left">{{ model.verbose_name|title }}</td>
							<td onclick="toggle('chk_{{ exportable.name }}_{{ label }}_{{ forloop.counter }}');">{{ model.db_table }}</td>
							<td onclick="toggle('chk_{{ exportable.name }}_{{ label }}_{{ forloop.counter }}');" class="text text-nowrap text-right">{{ exportable.verbose_name }}</td>
						</tr>
					{% endfor %}
				{% endif %}
			{% endfor %}
			</table>
			</div>
			</div>
			</div>

		{% endfor %}

		</div>

	 		<div class="panel panel-warning">
	 		<div class="panel-heading clearfix">
	 			<i class="fas fa-file-export fa-fw fa-lg"></i> <button type="submit" class="btn btn-primary btn-sm pull-right">Export Selected</button>
	 		</div>
	 		</div>

		</form>
		</div>
		</div>
		</div>
	{% endif %}
{% endif %}

{% endif %}

{% endblock main %}

edc_export/templates/edc_export/bootstrap3/home.html
{% extends edc_base_template %}
{% load static %}

{% block main %}

{{ block.super }}

  <div class="col-sm-4">&nbsp;
  </div>

  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">Export</div>


      <div class="list-group">
      {% if perms.edc_dashboard.view_export_dashboard %}
        <a id="home_list_group_home" href="{% url 'home_url' %}" class="list-group-item"><i class="fas fa-reply fa-1x fa-fw" aria-hidden="true"></i> Home</a>
        <a id="home_list_group_export_data" href="{% url 'edc_export:export_models_url' %}" class="list-group-item">Export data</a>
        <a id="home_list_group_export_admin" href="{% url 'edc_export:edc_export_admin:index' %}" class="list-group-item">Administration</a>
      {% endif %}
      </div>
    </div>
  </div>

  <div class="col-sm-4">&nbsp;
  </div>
{% endblock main %}